services:
  postgres:
    image: postgres:16.4-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: audriver
      PGUSER: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
      TZ: Asia/Tokyo
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost" ]
      interval: 3s
      retries: 5
      start_period: 30s
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      default:

volumes:
  postgres:
